name: Windows Qt5.15 Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    environment: Windows Qt5.15

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Clone the necessary repositories
      - name: Clone ci-utilities
        run: git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1

      - name: Clone repo-metadata
        run: git clone https://invent.kde.org/sysadmin/repo-metadata.git ci-utilities/repo-metadata/ --depth=1

      # Set environment variables
      env:
        KDECI_CACHE_PATH: C:/Gitlab/Artifacts/windows-qt5.15/
        KDECI_GITLAB_SERVER: https://invent.kde.org/
        KDECI_PACKAGE_PROJECT: teams/ci-artifacts/windows-qt5.15
        CRAFT_ROOT: C:/Craft/windows-msvc2019_64-cl/
        CXX: cl.exe
        CC: cl.exe
        PYTHONUTF8: 1

      # Setup MSVC environment and run the build script
      - name: Setup MSVC Environment
        shell: pwsh
        run: . ci-utilities/resources/setup-msvc-env.ps1

      - name: Run CI Build Script
        run: python -u ci-utilities/run-ci-build.py --project ${{ github.event.repository.name }} --branch ${{ github.ref_name }} --platform Windows/Qt5/Shared

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JUnitTestResults
          path: JUnitTestResults.xml
          retention-days: 14

