name: Windows Qt5.15 Build with Docker
'on':
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          choco install docker-desktop --pre
          Start-Service docker

      - name: Pull Docker Image
        run: >-
          docker pull
          invent-registry.kde.org/sysadmin/ci-images/windows-msvc2019-qt515:latest

      - name: Run Build in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \

          invent-registry.kde.org/sysadmin/ci-images/windows-msvc2019-qt515:latest
          \

          powershell -Command "

          git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1;

          git clone https://invent.kde.org/sysadmin/repo-metadata.git
          ci-utilities/repo-metadata/ --depth=1;

          . ci-utilities/resources/setup-msvc-env.ps1;

          python -u ci-utilities/run-ci-build.py --project ${{
          github.event.repository.name }} --branch ${{ github.ref_name }}
          --platform Windows/Qt5/Shared;

          "

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JUnitTestResults
          path: JUnitTestResults.xml
          retention-days: 14
